package permissions

// Permission constants - all permissions in CAPS_LOCK format
const (
	// Dog Permissions
	DOGS_CREATE      = "DOGS_CREATE"
	DOGS_VIEW_OWN    = "DOGS_VIEW_OWN"
	DOGS_VIEW_ASSIGNED = "DOGS_VIEW_ASSIGNED"
	DOGS_VIEW_ALL    = "DOGS_VIEW_ALL"
	DOGS_UPDATE_OWN  = "DOGS_UPDATE_OWN"
	DOGS_UPDATE_ALL  = "DOGS_UPDATE_ALL"
	DOGS_DELETE_OWN  = "DOGS_DELETE_OWN"
	DOGS_DELETE_ALL  = "DOGS_DELETE_ALL"

	// Event Permissions
	EVENTS_CREATE_OWN      = "EVENTS_CREATE_OWN"
	EVENTS_CREATE_ASSIGNED = "EVENTS_CREATE_ASSIGNED"
	EVENTS_CREATE_ALL      = "EVENTS_CREATE_ALL"
	EVENTS_VIEW_OWN        = "EVENTS_VIEW_OWN"
	EVENTS_VIEW_ASSIGNED   = "EVENTS_VIEW_ASSIGNED"
	EVENTS_VIEW_ALL        = "EVENTS_VIEW_ALL"
	EVENTS_DELETE_OWN      = "EVENTS_DELETE_OWN"
	EVENTS_DELETE_ALL      = "EVENTS_DELETE_ALL"

	// Event Comment Permissions
	EVENT_COMMENTS_CREATE_OWN      = "EVENT_COMMENTS_CREATE_OWN"
	EVENT_COMMENTS_CREATE_ASSIGNED = "EVENT_COMMENTS_CREATE_ASSIGNED"
	EVENT_COMMENTS_VIEW_OWN        = "EVENT_COMMENTS_VIEW_OWN"
	EVENT_COMMENTS_VIEW_ASSIGNED   = "EVENT_COMMENTS_VIEW_ASSIGNED"
	EVENT_COMMENTS_UPDATE_AUTHORED = "EVENT_COMMENTS_UPDATE_AUTHORED"
	EVENT_COMMENTS_DELETE_AUTHORED = "EVENT_COMMENTS_DELETE_AUTHORED"
	EVENT_COMMENTS_DELETE_ALL      = "EVENT_COMMENTS_DELETE_ALL"

	// Consultant Note Permissions
	CONSULTANT_NOTES_CREATE     = "CONSULTANT_NOTES_CREATE"
	CONSULTANT_NOTES_VIEW_OWN   = "CONSULTANT_NOTES_VIEW_OWN"
	CONSULTANT_NOTES_VIEW_ALL   = "CONSULTANT_NOTES_VIEW_ALL"
	CONSULTANT_NOTES_UPDATE_OWN = "CONSULTANT_NOTES_UPDATE_OWN"
	CONSULTANT_NOTES_DELETE_OWN = "CONSULTANT_NOTES_DELETE_OWN"
	CONSULTANT_NOTES_DELETE_ALL = "CONSULTANT_NOTES_DELETE_ALL"

	// Consultant Permissions
	CONSULTANTS_SEARCH         = "CONSULTANTS_SEARCH"
	CONSULTANTS_INVITE         = "CONSULTANTS_INVITE"
	CONSULTANTS_PROFILE_UPDATE = "CONSULTANTS_PROFILE_UPDATE"
	CONSULTANTS_INVITES_ACCEPT = "CONSULTANTS_INVITES_ACCEPT"

	// User Permissions
	USERS_VIEW_OWN   = "USERS_VIEW_OWN"
	USERS_VIEW_ALL   = "USERS_VIEW_ALL"
	USERS_UPDATE_OWN = "USERS_UPDATE_OWN"
	USERS_UPDATE_ALL = "USERS_UPDATE_ALL"
	USERS_DELETE_ALL = "USERS_DELETE_ALL"
)

// AllPermissions lists all available permissions in the system
var AllPermissions = []string{
	DOGS_CREATE,
	DOGS_VIEW_OWN,
	DOGS_VIEW_ASSIGNED,
	DOGS_VIEW_ALL,
	DOGS_UPDATE_OWN,
	DOGS_UPDATE_ALL,
	DOGS_DELETE_OWN,
	DOGS_DELETE_ALL,
	EVENTS_CREATE_OWN,
	EVENTS_CREATE_ASSIGNED,
	EVENTS_CREATE_ALL,
	EVENTS_VIEW_OWN,
	EVENTS_VIEW_ASSIGNED,
	EVENTS_VIEW_ALL,
	EVENTS_DELETE_OWN,
	EVENTS_DELETE_ALL,
	EVENT_COMMENTS_CREATE_OWN,
	EVENT_COMMENTS_CREATE_ASSIGNED,
	EVENT_COMMENTS_VIEW_OWN,
	EVENT_COMMENTS_VIEW_ASSIGNED,
	EVENT_COMMENTS_UPDATE_AUTHORED,
	EVENT_COMMENTS_DELETE_AUTHORED,
	EVENT_COMMENTS_DELETE_ALL,
	CONSULTANT_NOTES_CREATE,
	CONSULTANT_NOTES_VIEW_OWN,
	CONSULTANT_NOTES_VIEW_ALL,
	CONSULTANT_NOTES_UPDATE_OWN,
	CONSULTANT_NOTES_DELETE_OWN,
	CONSULTANT_NOTES_DELETE_ALL,
	CONSULTANTS_SEARCH,
	CONSULTANTS_INVITE,
	CONSULTANTS_PROFILE_UPDATE,
	CONSULTANTS_INVITES_ACCEPT,
	USERS_VIEW_OWN,
	USERS_VIEW_ALL,
	USERS_UPDATE_OWN,
	USERS_UPDATE_ALL,
	USERS_DELETE_ALL,
}

// OwnerPermissions defines default permissions for owner role
var OwnerPermissions = []string{
	DOGS_CREATE,
	DOGS_VIEW_OWN,
	DOGS_UPDATE_OWN,
	DOGS_DELETE_OWN,
	EVENTS_CREATE_OWN,
	EVENTS_VIEW_OWN,
	EVENTS_DELETE_OWN,
	EVENT_COMMENTS_CREATE_OWN,
	EVENT_COMMENTS_VIEW_OWN,
	EVENT_COMMENTS_UPDATE_AUTHORED,
	EVENT_COMMENTS_DELETE_AUTHORED,
	CONSULTANTS_SEARCH,
	CONSULTANTS_INVITE,
	USERS_VIEW_OWN,
	USERS_UPDATE_OWN,
}

// ConsultantBasePermissions defines base permissions for consultant role (before invitation)
var ConsultantBasePermissions = []string{
	CONSULTANTS_PROFILE_UPDATE,
	CONSULTANTS_INVITES_ACCEPT,
	CONSULTANTS_SEARCH,
	USERS_VIEW_OWN,
	USERS_UPDATE_OWN,
}

// ConsultantAssignedPermissions defines additional permissions granted when consultant accepts invitation
var ConsultantAssignedPermissions = []string{
	DOGS_VIEW_ASSIGNED,
	EVENTS_CREATE_ASSIGNED,
	EVENTS_VIEW_ASSIGNED,
	EVENT_COMMENTS_CREATE_ASSIGNED,
	EVENT_COMMENTS_VIEW_ASSIGNED,
	EVENT_COMMENTS_UPDATE_AUTHORED,
	EVENT_COMMENTS_DELETE_AUTHORED,
	CONSULTANT_NOTES_CREATE,
	CONSULTANT_NOTES_VIEW_OWN,
	CONSULTANT_NOTES_UPDATE_OWN,
	CONSULTANT_NOTES_DELETE_OWN,
}

// AdminPermissions defines all permissions for admin role (explicit list)
var AdminPermissions = []string{
	DOGS_CREATE,
	DOGS_VIEW_OWN,
	DOGS_VIEW_ASSIGNED,
	DOGS_VIEW_ALL,
	DOGS_UPDATE_OWN,
	DOGS_UPDATE_ALL,
	DOGS_DELETE_OWN,
	DOGS_DELETE_ALL,
	EVENTS_CREATE_OWN,
	EVENTS_CREATE_ASSIGNED,
	EVENTS_CREATE_ALL,
	EVENTS_VIEW_OWN,
	EVENTS_VIEW_ASSIGNED,
	EVENTS_VIEW_ALL,
	EVENTS_DELETE_OWN,
	EVENTS_DELETE_ALL,
	EVENT_COMMENTS_CREATE_OWN,
	EVENT_COMMENTS_CREATE_ASSIGNED,
	EVENT_COMMENTS_VIEW_OWN,
	EVENT_COMMENTS_VIEW_ASSIGNED,
	EVENT_COMMENTS_UPDATE_AUTHORED,
	EVENT_COMMENTS_DELETE_AUTHORED,
	EVENT_COMMENTS_DELETE_ALL,
	CONSULTANT_NOTES_CREATE,
	CONSULTANT_NOTES_VIEW_OWN,
	CONSULTANT_NOTES_VIEW_ALL,
	CONSULTANT_NOTES_UPDATE_OWN,
	CONSULTANT_NOTES_DELETE_OWN,
	CONSULTANT_NOTES_DELETE_ALL,
	CONSULTANTS_SEARCH,
	CONSULTANTS_INVITE,
	CONSULTANTS_PROFILE_UPDATE,
	CONSULTANTS_INVITES_ACCEPT,
	USERS_VIEW_OWN,
	USERS_VIEW_ALL,
	USERS_UPDATE_OWN,
	USERS_UPDATE_ALL,
	USERS_DELETE_ALL,
}
